import {
  BetEntryRecord,
  BetOptionRecord,
  BetOptionMode,
  BetRecord,
  BridgeClientRecord,
  CatalogItemRecord,
  CreatorSuggestionBoostRecord,
  CreatorSuggestionRecord,
  GameSuggestionBoostRecord,
  GameSuggestionRecord,
  GoogleAccountRecord,
  GoogleAccountViewerRecord,
  GoogleRiscDeliveryRecord,
  LedgerEntryRecord,
  QuoteRecord,
  ProductRecommendationRecord,
  RedemptionRecord,
  VideoSuggestionBoostRecord,
  VideoSuggestionRecord,
  ViewerBalanceRecord,
  ViewerRecord,
} from "@/lib/types";

const now = new Date();

export const demoViewers: ViewerRecord[] = [
  {
    id: "viewer_ana",
    googleUserId: "google_ana",
    email: "ana@example.com",
    youtubeChannelId: "yt_ana",
    youtubeDisplayName: "Ana Neon",
    youtubeHandle: "@ananeon",
    avatarUrl:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80",
    isLinked: true,
    excludeFromRanking: false,
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: "viewer_caio",
    googleUserId: "google_caio",
    email: "caio@example.com",
    youtubeChannelId: "yt_caio",
    youtubeDisplayName: "Caio CRT",
    youtubeHandle: "@caiocrt",
    avatarUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
    isLinked: true,
    excludeFromRanking: false,
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "viewer_lia",
    googleUserId: null,
    email: null,
    youtubeChannelId: "yt_lia",
    youtubeDisplayName: "Lia Pixel",
    youtubeHandle: "@liapixel",
    avatarUrl:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80",
    isLinked: false,
    excludeFromRanking: false,
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 12).toISOString(),
  },
];

export const demoGoogleAccounts: GoogleAccountRecord[] = [
  {
    id: "ga_ana",
    googleUserId: "google_ana",
    email: "ana@example.com",
    displayName: "Ana",
    avatarUrl:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80",
    activeViewerId: "viewer_ana",
    crossAccountProtectionState: "ok",
    crossAccountProtectionEvent: null,
    crossAccountProtectionReason: null,
    crossAccountProtectionUpdatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    sessionsRevokedAt: null,
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: "ga_caio",
    googleUserId: "google_caio",
    email: "caio@example.com",
    displayName: "Caio",
    avatarUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
    activeViewerId: "viewer_caio",
    crossAccountProtectionState: "ok",
    crossAccountProtectionEvent: null,
    crossAccountProtectionReason: null,
    crossAccountProtectionUpdatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    sessionsRevokedAt: null,
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
];

export const demoGoogleAccountViewers: GoogleAccountViewerRecord[] = [
  {
    id: "gav_ana_1",
    googleAccountId: "ga_ana",
    viewerId: "viewer_ana",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: "gav_caio_1",
    googleAccountId: "ga_caio",
    viewerId: "viewer_caio",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
];

export const demoGoogleRiscDeliveries: GoogleRiscDeliveryRecord[] = [];

export const demoBalances: ViewerBalanceRecord[] = [
  {
    viewerId: "viewer_ana",
    currentBalance: 1420,
    lifetimeEarned: 1880,
    lifetimeSpent: 460,
    lastSyncedAt: now.toISOString(),
  },
  {
    viewerId: "viewer_caio",
    currentBalance: 980,
    lifetimeEarned: 1260,
    lifetimeSpent: 280,
    lastSyncedAt: now.toISOString(),
  },
  {
    viewerId: "viewer_lia",
    currentBalance: 520,
    lifetimeEarned: 620,
    lifetimeSpent: 100,
    lastSyncedAt: now.toISOString(),
  },
];

export const demoCatalog: CatalogItemRecord[] = [
  {
    id: "item_horn",
    slug: "buzina-neon",
    name: "Buzina Neon",
    description: "Toca uma vinheta curta para cortar o caos da live.",
    type: "play_sound",
    cost: 180,
    isActive: true,
    globalCooldownSeconds: 15,
    viewerCooldownSeconds: 60,
    stock: null,
    previewImageUrl:
      "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=900&q=80",
    accentColor: "#b4ff39",
    isFeatured: true,
    streamerbotActionRef: "Play Approved Sound",
    streamerbotArgsTemplate: { soundKey: "neon_horn" },
  },
  {
    id: "item_flash",
    slug: "flash-na-tela",
    name: "Flash na Tela",
    description: "Aciona um overlay agressivo no palco digital.",
    type: "overlay_scene_trigger",
    cost: 250,
    isActive: true,
    globalCooldownSeconds: 25,
    viewerCooldownSeconds: 90,
    stock: null,
    previewImageUrl:
      "https://images.unsplash.com/photo-1520034475321-cbe63696469a?auto=format&fit=crop&w=900&q=80",
    accentColor: "#00e7ff",
    isFeatured: true,
    streamerbotActionRef: "Trigger Overlay Scene",
    streamerbotArgsTemplate: { sceneKey: "flash_brutalist" },
  },
  {
    id: "item_sticker",
    slug: "sticker-holografico",
    name: "Sticker Holográfico",
    description: "Mostra uma arte aprovada no overlay por alguns segundos.",
    type: "show_image",
    cost: 320,
    isActive: true,
    globalCooldownSeconds: 20,
    viewerCooldownSeconds: 120,
    stock: 20,
    previewImageUrl:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80",
    accentColor: "#ff46e0",
    isFeatured: false,
    streamerbotActionRef: "Show Approved Image",
    streamerbotArgsTemplate: { imageKey: "holo_sticker" },
  },
];

export const demoProductRecommendations: ProductRecommendationRecord[] = [];

export const demoLedger: LedgerEntryRecord[] = [
  {
    id: "ledger_1",
    viewerId: "viewer_ana",
    kind: "presence_tick",
    amount: 5,
    source: "streamerbot",
    externalEventId: "evt_presence_1",
    metadata: { liveId: "live_demo" },
    createdAt: new Date(now.getTime() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: "ledger_2",
    viewerId: "viewer_caio",
    kind: "chat_bonus",
    amount: 2,
    source: "streamerbot",
    externalEventId: "evt_chat_1",
    metadata: { liveId: "live_demo" },
    createdAt: new Date(now.getTime() - 1000 * 60 * 2).toISOString(),
  },
];

export const demoRedemptions: RedemptionRecord[] = [
  {
    id: "red_1",
    viewerId: "viewer_ana",
    catalogItemId: "item_horn",
    status: "completed",
    costAtPurchase: 180,
    requestSource: "web",
    idempotencyKey: "idem_red_1",
    bridgeAttemptCount: 1,
    claimedByBridgeId: "bridge_local",
    queuedAt: new Date(now.getTime() - 1000 * 60 * 30).toISOString(),
    executedAt: new Date(now.getTime() - 1000 * 60 * 29).toISOString(),
    failedAt: null,
    failureReason: null,
  },
  {
    id: "red_2",
    viewerId: "viewer_caio",
    catalogItemId: "item_flash",
    status: "queued",
    costAtPurchase: 250,
    requestSource: "web",
    idempotencyKey: "idem_red_2",
    bridgeAttemptCount: 0,
    claimedByBridgeId: null,
    queuedAt: new Date(now.getTime() - 1000 * 60).toISOString(),
    executedAt: null,
    failedAt: null,
    failureReason: null,
  },
];

export const demoBridgeClients: BridgeClientRecord[] = [
  {
    id: "bridge_local",
    machineKey: "dev-machine",
    label: "PC da Stream",
    lastSeenAt: now.toISOString(),
  },
];

export const demoQuotes: QuoteRecord[] = [
  {
    id: "quote_1",
    quoteNumber: 1,
    body: "isso aqui vai dar muito certo, confia",
    createdByViewerId: "viewer_ana",
    createdByDisplayName: "Ana Neon",
    createdByYoutubeHandle: "@ananeon",
    source: "streamerbot_chat",
    createdAt: new Date(now.getTime() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: "quote_2",
    quoteNumber: 2,
    body: "se eu morrer, foi estrategia",
    createdByViewerId: "viewer_caio",
    createdByDisplayName: "Caio CRT",
    createdByYoutubeHandle: "@caiocrt",
    source: "streamerbot_chat",
    createdAt: new Date(now.getTime() - 1000 * 60 * 45).toISOString(),
  },
];

// ── Bets (mock) ──

export interface DemoBetOption {
  id: string;
  label: string;
  poolAmount: number;
}

export interface DemoBet {
  id: string;
  question: string;
  optionMode?: BetOptionMode;
  status: "open" | "locked" | "resolved" | "cancelled";
  deadline: Date;
  totalPool: number;
  winningOptionId?: string;
  options: DemoBetOption[];
}

export const demoBets: DemoBet[] = [
  {
    id: "bet-1",
    question: "Ela vai zerar o boss sem morrer?",
    status: "open",
    deadline: new Date(Date.now() + 2 * 60 * 60 * 1000),
    totalPool: 4650,
    options: [
      { id: "opt-1a", label: "Sim, first try!", poolAmount: 1250 },
      { id: "opt-1b", label: "Vai morrer pelo menos 3x", poolAmount: 3400 },
    ],
  },
  {
    id: "bet-2",
    question: "Quanto tempo ate zerar o jogo?",
    status: "resolved",
    deadline: new Date(Date.now() - 24 * 60 * 60 * 1000),
    totalPool: 8200,
    winningOptionId: "opt-2b",
    options: [
      { id: "opt-2a", label: "Menos de 5h", poolAmount: 2100 },
      { id: "opt-2b", label: "5-10h", poolAmount: 4800 },
      { id: "opt-2c", label: "Mais de 10h", poolAmount: 1300 },
    ],
  },
  {
    id: "bet-3",
    question: "Vai achar o item secreto na live de hoje?",
    status: "open",
    deadline: new Date(Date.now() + 45 * 60 * 1000),
    totalPool: 1820,
    options: [
      { id: "opt-3a", label: "Acha facil", poolAmount: 320 },
      { id: "opt-3b", label: "Demora mas acha", poolAmount: 980 },
      { id: "opt-3c", label: "Nem encontra", poolAmount: 520 },
    ],
  },
];

export const demoBetRecords: BetRecord[] = demoBets.map((bet) => ({
  id: bet.id,
  question: bet.question,
  optionMode: bet.optionMode ?? "preset",
  status: bet.status,
  openedAt: new Date(now.getTime() - 15 * 60 * 1000).toISOString(),
  closesAt: bet.deadline.toISOString(),
  lockedAt: bet.status === "locked" || bet.status === "resolved" ? bet.deadline.toISOString() : null,
  resolvedAt: bet.status === "resolved" ? new Date(now.getTime() - 5 * 60 * 1000).toISOString() : null,
  cancelledAt: bet.status === "cancelled" ? new Date(now.getTime() - 5 * 60 * 1000).toISOString() : null,
  winningOptionId: bet.winningOptionId ?? null,
  createdAt: new Date(now.getTime() - 30 * 60 * 1000).toISOString(),
}));

export const demoBetOptions: BetOptionRecord[] = demoBets.flatMap((bet) =>
  bet.options.map((option, index) => ({
    id: option.id,
    betId: bet.id,
    label: option.label,
    sortOrder: index,
    poolAmount: option.poolAmount,
  })),
);

export const demoBetEntries: BetEntryRecord[] = [
  {
    id: "bet-entry-1",
    betId: "bet-2",
    optionId: "opt-2b",
    viewerId: "viewer_ana",
    amount: 400,
    isHouseEntry: false,
    payoutAmount: 683,
    settledAt: new Date(now.getTime() - 23 * 60 * 60 * 1000).toISOString(),
    refundedAt: null,
    createdAt: new Date(now.getTime() - 29 * 60 * 60 * 1000).toISOString(),
  },
];

// ── Game Suggestions (mock) ──

export const demoGameSuggestions: GameSuggestionRecord[] = [
  {
    id: "gs-ps-plus-demo",
    viewerId: "viewer_lia",
    slug: "warhammer-40000-space-marine-2",
    name: "Warhammer 40,000: Space Marine 2",
    description: "Exemplo de indicação marcada como disponível no catálogo PS Plus Deluxe.",
    linkUrl: null,
    igdbId: null,
    canonicalName: "Warhammer 40,000: Space Marine 2",
    coverImageUrl: null,
    releaseYear: 2024,
    platforms: ["PlayStation 5"],
    genres: ["Action", "Shooter"],
    howLongToBeat: null,
    psPlusAvailable: true,
    psPlusRegion: "pt-br",
    psPlusTier: "deluxe",
    psPlusProductId: "UP4133-PPSA04452_00-SPACEMARINESII00",
    psPlusTitleId: "PPSA04452_00",
    psPlusProductUrl: "https://store.playstation.com/pt-br/product/UP4133-PPSA04452_00-SPACEMARINESII00",
    psPlusCheckedAt: now.toISOString(),
    psPlusLastSeenAt: now.toISOString(),
    steamStore: {
      appId: 2183900,
      name: "Warhammer 40,000: Space Marine 2",
      storeUrl: "https://store.steampowered.com/app/2183900",
      currency: "BRL",
      initialPriceCents: 22990,
      finalPriceCents: 18392,
      discountPercent: 20,
      isFree: false,
      matchConfidence: "exact_name",
      checkedAt: now.toISOString(),
      lastPriceAt: now.toISOString(),
    },
    totalVotes: 4100,
    status: "open",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 80).toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: "gs-1",
    viewerId: "viewer_ana",
    slug: "hollow-knight-silksong",
    name: "Hollow Knight: Silksong",
    description: "Quando sair, bora de day one!",
    linkUrl: null,
    igdbId: 119388,
    canonicalName: "Hollow Knight: Silksong",
    coverImageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co8hpl.jpg",
    releaseYear: 2025,
    platforms: ["PC", "Nintendo Switch"],
    genres: ["Platform", "Adventure"],
    howLongToBeat: null,
    psPlusAvailable: false,
    psPlusRegion: null,
    psPlusTier: null,
    psPlusProductId: null,
    psPlusTitleId: null,
    psPlusProductUrl: null,
    psPlusCheckedAt: null,
    psPlusLastSeenAt: null,
    steamStore: null,
    totalVotes: 3200,
    status: "open",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 72).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: "gs-2",
    viewerId: "viewer_caio",
    slug: "celeste",
    name: "Celeste",
    description: "Platformer indie que vai te fazer chorar e xingar ao mesmo tempo",
    linkUrl: null,
    igdbId: 20342,
    canonicalName: "Celeste",
    coverImageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3byy.jpg",
    releaseYear: 2018,
    platforms: ["PC", "Nintendo Switch"],
    genres: ["Platform", "Adventure"],
    howLongToBeat: {
      id: "42818",
      name: "Celeste",
      mainStoryMinutes: 510,
      mainExtraMinutes: 870,
      completionistMinutes: 2220,
      similarity: 1,
      fetchedAt: new Date(now.getTime() - 1000 * 60 * 60 * 3).toISOString(),
    },
    psPlusAvailable: false,
    psPlusRegion: null,
    psPlusTier: null,
    psPlusProductId: null,
    psPlusTitleId: null,
    psPlusProductUrl: null,
    psPlusCheckedAt: null,
    psPlusLastSeenAt: null,
    steamStore: {
      appId: 504230,
      name: "Celeste",
      storeUrl: "https://store.steampowered.com/app/504230",
      currency: "BRL",
      initialPriceCents: 3699,
      finalPriceCents: 924,
      discountPercent: 75,
      isFree: false,
      matchConfidence: "exact_name",
      checkedAt: now.toISOString(),
      lastPriceAt: now.toISOString(),
    },
    totalVotes: 1800,
    status: "accepted",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 54).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    id: "gs-3",
    viewerId: "viewer_lia",
    slug: "elden-ring-dlc",
    name: "Elden Ring DLC",
    description: "Shadow of the Erdtree, pra sofrer junto",
    linkUrl: null,
    igdbId: null,
    canonicalName: null,
    coverImageUrl: null,
    releaseYear: null,
    platforms: [],
    genres: [],
    howLongToBeat: {
      id: null,
      name: null,
      mainStoryMinutes: null,
      mainExtraMinutes: null,
      completionistMinutes: null,
      similarity: null,
      fetchedAt: new Date(now.getTime() - 1000 * 60 * 60 * 5).toISOString(),
    },
    psPlusAvailable: false,
    psPlusRegion: null,
    psPlusTier: null,
    psPlusProductId: null,
    psPlusTitleId: null,
    psPlusProductUrl: null,
    psPlusCheckedAt: null,
    psPlusLastSeenAt: null,
    steamStore: null,
    totalVotes: 2950,
    status: "played",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 44).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 10).toISOString(),
  },
  {
    id: "gs-4",
    viewerId: "viewer_caio",
    slug: "hades-ii",
    name: "Hades II",
    description: "Early access já está incrível",
    linkUrl: null,
    igdbId: 240007,
    canonicalName: "Hades II",
    coverImageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co88ac.jpg",
    releaseYear: 2024,
    platforms: ["PC"],
    genres: ["Role-playing", "Hack and slash"],
    howLongToBeat: {
      id: "126016",
      name: "Hades II",
      mainStoryMinutes: 1620,
      mainExtraMinutes: 2880,
      completionistMinutes: 5160,
      similarity: 1,
      fetchedAt: new Date(now.getTime() - 1000 * 60 * 60 * 4).toISOString(),
    },
    psPlusAvailable: false,
    psPlusRegion: null,
    psPlusTier: null,
    psPlusProductId: null,
    psPlusTitleId: null,
    psPlusProductUrl: null,
    psPlusCheckedAt: null,
    psPlusLastSeenAt: null,
    steamStore: null,
    totalVotes: 1200,
    status: "open",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 20).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "gs-5",
    viewerId: "viewer_ana",
    slug: "outer-wilds",
    name: "Outer Wilds",
    description: "Melhor jogo de exploração que existe. Sem spoilers!",
    linkUrl: null,
    igdbId: 11156,
    canonicalName: "Outer Wilds",
    coverImageUrl: "https://images.igdb.com/igdb/image/upload/t_cover_big/co65ac.jpg",
    releaseYear: 2019,
    platforms: ["PC", "PlayStation 4"],
    genres: ["Adventure", "Puzzle"],
    howLongToBeat: {
      id: "57527",
      name: "Outer Wilds",
      mainStoryMinutes: 990,
      mainExtraMinutes: 1320,
      completionistMinutes: 1590,
      similarity: 1,
      fetchedAt: new Date(now.getTime() - 1000 * 60 * 60 * 2).toISOString(),
    },
    psPlusAvailable: false,
    psPlusRegion: null,
    psPlusTier: null,
    psPlusProductId: null,
    psPlusTitleId: null,
    psPlusProductUrl: null,
    psPlusCheckedAt: null,
    psPlusLastSeenAt: null,
    steamStore: null,
    totalVotes: 890,
    status: "open",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 12).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 20).toISOString(),
  },
];

export const demoGameSuggestionBoosts: GameSuggestionBoostRecord[] = [];

export const demoCreatorSuggestions: CreatorSuggestionRecord[] = [
  {
    id: "cs-featured-rosadiariogamer",
    viewerId: "viewer_lia",
    slug: "rosadiariogamer",
    name: "Rosa Diário Gamer",
    channelUrl: "https://www.youtube.com/@rosadiariogamer",
    platform: "youtube",
    category: "games",
    reason: "Canal de games com energia próxima, presença de comunidade e um jeito gostoso de acompanhar gameplay.",
    totalVotes: 1210,
    status: "featured",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 61).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 61).toISOString(),
  },
  {
    id: "cs-featured-brksedu",
    viewerId: "viewer_lia",
    slug: "brksedu",
    name: "BRKsEDU",
    channelUrl: "https://www.youtube.com/@BRKsEDU",
    platform: "youtube",
    category: "games",
    reason: "Gameplay, carisma e repertório de jogos com aquele ritmo bom de acompanhar por horas.",
    totalVotes: 1200,
    status: "featured",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 60).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 60).toISOString(),
  },
  {
    id: "cs-featured-cogumelando",
    viewerId: "viewer_lia",
    slug: "cogumelando",
    name: "Cogumelando",
    channelUrl: "https://www.youtube.com/@cogumelando",
    platform: "youtube",
    category: "videogame",
    reason: "Olhar acolhedor e muito vivido sobre videogame, com carinho por história, descoberta e comunidade.",
    totalVotes: 1190,
    status: "featured",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 59).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 59).toISOString(),
  },
  {
    id: "cs-featured-republica-coisa-de-nerd",
    viewerId: "viewer_lia",
    slug: "republica-coisa-de-nerd",
    name: "República Coisa de Nerd",
    channelUrl: "https://www.youtube.com/@republicacoisadenerd",
    platform: "youtube",
    category: "games e cultura pop",
    reason: "Conteúdo de jogos com energia leve, conversa boa e uma sensação gostosa de acompanhar junto.",
    totalVotes: 1180,
    status: "featured",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 58).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 58).toISOString(),
  },
  {
    id: "cs-featured-pablitto",
    viewerId: "viewer_lia",
    slug: "pablitto",
    name: "Pablitto",
    channelUrl: "https://www.youtube.com/@pablitto",
    platform: "youtube",
    category: "variedades",
    reason: "Live com presença, improviso e aquela troca rápida que faz o chat virar parte do conteúdo.",
    totalVotes: 1170,
    status: "featured",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 57).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 57).toISOString(),
  },
  {
    id: "cs-featured-funky-black-cat",
    viewerId: "viewer_lia",
    slug: "funky-black-cat",
    name: "Funky Black Cat",
    channelUrl: "https://www.youtube.com/@funkyblackcat",
    platform: "youtube",
    category: "games",
    reason: "Gameplay brasileiro clássico, com personalidade forte e uma história gigante no YouTube de jogos.",
    totalVotes: 1160,
    status: "featured",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 56).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 56).toISOString(),
  },
  {
    id: "cs-featured-pewdiepie",
    viewerId: "viewer_lia",
    slug: "pewdiepie",
    name: "PewDiePie",
    channelUrl: "https://www.youtube.com/@PewDiePie",
    platform: "youtube",
    category: "variedades",
    reason: "Um dos grandes nomes da cultura de criadores, com fases diferentes e muita influência no formato.",
    totalVotes: 1150,
    status: "featured",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 55).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 55).toISOString(),
  },
  {
    id: "cs-featured-striketps",
    viewerId: "viewer_lia",
    slug: "striketps",
    name: "StrikeTPS",
    channelUrl: "https://www.youtube.com/@StrikeTPS",
    platform: "youtube",
    category: "games",
    reason: "Conteúdo de jogos com pegada direta, humor e boas referências para acompanhar gameplay.",
    totalVotes: 1140,
    status: "featured",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 54).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 54).toISOString(),
  },
  {
    id: "cs-featured-coltydog",
    viewerId: "viewer_lia",
    slug: "coltydog",
    name: "Coltydog",
    channelUrl: "https://www.youtube.com/@coltydog",
    platform: "youtube",
    category: "lives",
    reason: "Stream com ritmo próprio, comunidade presente e momentos que deixam a live com cara de encontro.",
    totalVotes: 1130,
    status: "featured",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 53).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 53).toISOString(),
  },
  {
    id: "cs-featured-cellbit",
    viewerId: "viewer_lia",
    slug: "cellbit",
    name: "Cellbit",
    channelUrl: "https://www.twitch.tv/cellbit",
    platform: "twitch",
    category: "rpg e mistério",
    reason: "Criação de mundos, mistério e narrativa com uma capacidade rara de transformar live em experiência.",
    totalVotes: 1120,
    status: "featured",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 52).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 52).toISOString(),
  },
  {
    id: "cs-featured-maximizando",
    viewerId: "viewer_lia",
    slug: "maximizando",
    name: "M4Ximizando",
    channelUrl: "https://www.youtube.com/m4ximizando",
    platform: "youtube",
    category: "games",
    reason: "Conteúdo para pensar jogo, estratégia e escolhas com uma pegada prática e fácil de acompanhar.",
    totalVotes: 1110,
    status: "featured",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 51).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 51).toISOString(),
  },
  {
    id: "cs-featured-bagi",
    viewerId: "viewer_lia",
    slug: "bagi",
    name: "Bagi",
    channelUrl: "https://www.twitch.tv/bagi",
    platform: "twitch",
    category: "variedades e rpg",
    reason: "Live com personalidade, presença forte e uma entrega que combina caos bom, afeto e narrativa.",
    totalVotes: 1100,
    status: "featured",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 50).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 50).toISOString(),
  },
  {
    id: "cs-featured-beta-boechat",
    viewerId: "viewer_lia",
    slug: "beta-boechat",
    name: "Beta Boechat",
    channelUrl: "https://www.youtube.com/@betaboechat",
    platform: "youtube",
    category: "variedades",
    reason: "Conteúdo com voz própria, boas conversas e um jeito sensível de olhar cultura, internet e pessoas.",
    totalVotes: 1090,
    status: "featured",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 49).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 49).toISOString(),
  },
  {
    id: "cs-featured-debyte-podcast",
    viewerId: "viewer_lia",
    slug: "debyte-podcast",
    name: "DeByte Podcast",
    channelUrl: "https://www.youtube.com/@debytepodcast",
    platform: "youtube",
    category: "podcast de games",
    reason: "Podcast sobre mídia, games, criação de conteúdo e tecnologia com conversa leve e bem informada.",
    totalVotes: 1080,
    status: "featured",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 48).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: "cs-1",
    viewerId: "viewer_lia",
    slug: "canal-pequena-grande-ideia",
    name: "Pequena Grande Ideia",
    channelUrl: "https://www.youtube.com/@pequenagrandeideia",
    platform: "youtube",
    category: "ensaios e cultura pop",
    reason: "Canal bom para descobrir videos longos, bem editados e cheios de pauta para live.",
    totalVotes: 700,
    status: "open",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 40).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 8).toISOString(),
  },
  {
    id: "cs-2",
    viewerId: "viewer_caio",
    slug: "streamer-cozy-games-br",
    name: "Cozy Games BR",
    channelUrl: "https://www.twitch.tv/cozygamesbr",
    platform: "twitch",
    category: "indies e cozy games",
    reason: "Lives tranquilas e com bastante jogo indie para conhecer.",
    totalVotes: 420,
    status: "featured",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 22).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 3).toISOString(),
  },
];

export const demoCreatorSuggestionBoosts: CreatorSuggestionBoostRecord[] = [];

export const demoVideoSuggestions: VideoSuggestionRecord[] = [
  {
    id: "vs-1",
    viewerId: "viewer_ana",
    youtubeVideoId: "dQw4w9WgXcQ",
    title: "Rick Astley - Never Gonna Give You Up (Official Video) (4K Remaster)",
    creatorName: "Rick Astley",
    thumbnailUrl: "https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    reason: "Classico absoluto pra reagir com o chat.",
    totalVotes: 900,
    status: "open",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 30).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 35).toISOString(),
  },
  {
    id: "vs-2",
    viewerId: "viewer_caio",
    youtubeVideoId: "M7lc1UVf-VE",
    title: "YouTube Developers Live: Embedded Web Player Customization",
    creatorName: "Google for Developers",
    thumbnailUrl: "https://i.ytimg.com/vi/M7lc1UVf-VE/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=M7lc1UVf-VE",
    reason: "Quero ver voce comentando o caos tecnico disso.",
    totalVotes: 520,
    status: "accepted",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 18).toISOString(),
    updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 3).toISOString(),
  },
];

export const demoVideoSuggestionBoosts: VideoSuggestionBoostRecord[] = [];
