INSERT INTO "product_recommendations" (
  "id",
  "slug",
  "name",
  "category",
  "context",
  "image_url",
  "href",
  "store_label",
  "link_kind",
  "is_active",
  "sort_order",
  "created_at",
  "updated_at"
)
VALUES
  (
    'prod-ludylops-cartao-memoria-kingston-128gb',
    'cartao-memoria-kingston-128gb',
    'Cartão de memória Kingston 128 GB',
    'perifericos',
    'Cartão microSD com adaptador para guardar capturas, arquivos, jogos compatíveis e backups do setup.',
    'https://http2.mlstatic.com/D_NQ_NP_634432-MLA100047350641_122025-O.webp',
    'https://meli.la/1VyTgCJ',
    'Mercado Livre',
    'affiliate',
    true,
    100,
    now(),
    now()
  ),
  (
    'prod-ludylops-lixeira-pedal-50l',
    'lixeira-pedal-50l',
    'Lixeira com pedal 50 L',
    'acessorios',
    'Lixeira grande com tampa e pedal para manter o cantinho de trabalho mais organizado no dia a dia.',
    'https://http2.mlstatic.com/D_NQ_NP_923478-MLB81616514996_012025-O.webp',
    'https://meli.la/18yJpnQ',
    'Mercado Livre',
    'affiliate',
    true,
    110,
    now(),
    now()
  ),
  (
    'prod-ludylops-varal-luz-15m',
    'varal-luz-15m',
    'Varal de luz externo 15 m',
    'acessorios',
    'Cordão de luz para deixar cenário, varanda ou espaço de gravação com iluminação mais aconchegante.',
    'https://http2.mlstatic.com/D_NQ_NP_620610-MLB107011706657_022026-O.webp',
    'https://meli.la/2N52h7x',
    'Mercado Livre',
    'affiliate',
    true,
    120,
    now(),
    now()
  ),
  (
    'prod-ludylops-mochila-astronauta-pet',
    'mochila-astronauta-pet',
    'Mochila astronauta para pets',
    'acessorios',
    'Mochila de transporte com visor para levar gato ou cachorro pequeno com mais segurança e ventilação.',
    'https://http2.mlstatic.com/D_NQ_NP_738931-MLA109629085688_042026-O.webp',
    'https://meli.la/2HmBvJD',
    'Mercado Livre',
    'affiliate',
    true,
    130,
    now(),
    now()
  ),
  (
    'prod-ludylops-tomada-inteligente-zigbee',
    'tomada-inteligente-zigbee',
    'Tomada inteligente Zigbee 16 A',
    'perifericos',
    'Tomada inteligente com medição de consumo para automatizar luzes e equipamentos do setup.',
    'https://http2.mlstatic.com/D_NQ_NP_856700-MLB89536456815_082025-O.webp',
    'https://meli.la/2GF7FQd',
    'Mercado Livre',
    'affiliate',
    true,
    140,
    now(),
    now()
  ),
  (
    'prod-ludylops-suporte-vassouras-inox',
    'suporte-vassouras-inox',
    'Suporte de vassouras em inox',
    'acessorios',
    'Organizador de parede para vassouras, cabos e acessórios de limpeza ficarem fora do caminho.',
    'https://http2.mlstatic.com/D_NQ_NP_812233-MLA99930208369_112025-O.webp',
    'https://meli.la/1JUEtoL',
    'Mercado Livre',
    'affiliate',
    true,
    150,
    now(),
    now()
  ),
  (
    'prod-ludylops-organizador-cabos-fita',
    'organizador-cabos-fita',
    'Organizador de cabos em fita',
    'perifericos',
    'Fitas reutilizáveis para prender cabos de mesa, fones, carregadores e periféricos sem virar bagunça.',
    'https://ae01.alicdn.com/kf/S91610f67faf6466f9ea57abe0ea53e7bD.jpg',
    'https://s.click.aliexpress.com/e/_c4aZo2SZ',
    'AliExpress',
    'affiliate',
    true,
    160,
    now(),
    now()
  ),
  (
    'prod-ludylops-deskmat-rosa',
    'deskmat-rosa',
    'Deskmat rosa impermeável',
    'perifericos',
    'Mousepad grande para proteger a mesa, melhorar o deslize do mouse e deixar o setup mais bonito.',
    'https://ae01.alicdn.com/kf/Se8622c9732ac4d03aad4dc05b8f514eeL.jpg',
    'https://s.click.aliexpress.com/e/_c4sdhyKv',
    'AliExpress',
    'affiliate',
    true,
    170,
    now(),
    now()
  ),
  (
    'prod-ludylops-estante-wire-porcelana',
    'estante-wire-porcelana',
    'Estante Wire Porcelana',
    'acessorios',
    'Estante decorativa para livros, caixas, consoles, colecionáveis e objetos que precisam ficar à mão.',
    'https://static-images-now.westwing.com.br/s/136357-9869-994861-1-catalog.jpg',
    'https://www.westwing.com.br/estante-wire-porcelana-136357.html',
    'Westwing',
    'external',
    true,
    180,
    now(),
    now()
  ),
  (
    'prod-ludylops-qcy-h3-anc',
    'qcy-h3-anc',
    'Fone QCY H3 ANC',
    'perifericos',
    'Headset Bluetooth com cancelamento de ruído para trabalhar, jogar e acompanhar conteúdo com conforto.',
    'https://ae01.alicdn.com/kf/S81a68d7cc93e4078940cd01fcee2b7c1g.jpg',
    'https://s.click.aliexpress.com/e/_c3AGzjN3',
    'AliExpress',
    'affiliate',
    true,
    190,
    now(),
    now()
  ),
  (
    'prod-ludylops-capa-controle-ps5-gato',
    'capa-controle-ps5-gato',
    'Capa de silicone para controle PS5',
    'videogames',
    'Capa macia com orelhinhas para proteger o DualSense e dar um toque fofo no controle.',
    'https://ae01.alicdn.com/kf/Sdb9eb38c09184302a286ffc39247f777E.jpg',
    'https://pt.aliexpress.com/item/1005007109501047.html?spm=a2g0o.order_list.order_list_main.55.1879caa4akOlIo&gatewayAdapt=glo2bra',
    'AliExpress',
    'external',
    true,
    200,
    now(),
    now()
  ),
  (
    'prod-ludylops-power-bank-i2go-20000mah',
    'power-bank-i2go-20000mah',
    'Power bank i2GO 20000 mAh',
    'perifericos',
    'Carregador portátil de alta capacidade para manter celular, acessórios e equipamentos carregados fora de casa.',
    'https://m.media-amazon.com/images/I/51sXTXpIA1S._AC_SL1000_.jpg',
    'https://amzn.to/3Rl0pAt',
    'Amazon',
    'affiliate',
    true,
    210,
    now(),
    now()
  ),
  (
    'prod-ludylops-lampada-smart-positivo-rgb',
    'lampada-smart-positivo-rgb',
    'Lâmpada smart Positivo RGB',
    'acessorios',
    'Lâmpada Wi-Fi com branco ajustável e RGB para controlar a iluminação do quarto ou do cenário.',
    'https://m.media-amazon.com/images/I/51sXUs-tZiL._AC_SL1000_.jpg',
    'https://amzn.to/4dGG3t1',
    'Amazon',
    'affiliate',
    true,
    220,
    now(),
    now()
  ),
  (
    'prod-ludylops-funocracy-jogo-cartas',
    'funocracy-jogo-cartas',
    'Funocracy jogo de cartas',
    'videogames',
    'Party game de cartas para jogar com grupo, puxar conversa e criar momentos caóticos na mesa.',
    'https://m.media-amazon.com/images/I/61eBlUu-ubL._AC_SL1080_.jpg',
    'https://amzn.to/4tMrCtm',
    'Amazon',
    'affiliate',
    true,
    230,
    now(),
    now()
  ),
  (
    'prod-ludylops-carregador-baseus-30w',
    'carregador-baseus-30w',
    'Carregador Baseus 30 W',
    'perifericos',
    'Carregador compacto com USB-C e USB-A para celular, acessórios e itens essenciais da mesa.',
    'https://m.media-amazon.com/images/I/61peaDmag1L._AC_SL1200_.jpg',
    'https://amzn.to/4wEinho',
    'Amazon',
    'affiliate',
    true,
    240,
    now(),
    now()
  ),
  (
    'prod-ludylops-filtro-linha-iclamper-8',
    'filtro-linha-iclamper-8',
    'Filtro de linha iCLAMPER 8 tomadas',
    'perifericos',
    'Filtro de linha com proteção contra surtos para ligar PC, monitor, console e acessórios com mais segurança.',
    'https://m.media-amazon.com/images/I/51egF2vkxML._AC_SL1200_.jpg',
    'https://amzn.to/43jUH4r',
    'Amazon',
    'affiliate',
    true,
    250,
    now(),
    now()
  ),
  (
    'prod-ludylops-barra-luz-monitor-quntis',
    'barra-luz-monitor-quntis',
    'Barra de luz para monitor Quntis',
    'perifericos',
    'Luz de monitor para iluminar a mesa sem ocupar espaço e reduzir incômodo nos olhos.',
    'https://m.media-amazon.com/images/I/51eonlX0beL._AC_SL1500_.jpg',
    'https://amzn.to/4urrW1U',
    'Amazon',
    'affiliate',
    true,
    260,
    now(),
    now()
  ),
  (
    'prod-ludylops-tripe-ulanzi-mt44',
    'tripe-ulanzi-mt44',
    'Tripé Ulanzi MT-44',
    'perifericos',
    'Tripé extensível com suporte para celular e câmera para gravação, foto e lives fora do lugar fixo.',
    'https://m.media-amazon.com/images/I/61WWQxfAdLL._AC_SL1500_.jpg',
    'https://amzn.to/3RSus2x',
    'Amazon',
    'affiliate',
    true,
    270,
    now(),
    now()
  ),
  (
    'prod-ludylops-bastao-luz-ulanzi-vl119',
    'bastao-luz-ulanzi-vl119',
    'Bastão de luz Ulanzi VL119',
    'perifericos',
    'Luz LED RGB portátil para fotos, vídeos, detalhes de cenário e iluminação criativa.',
    'https://m.media-amazon.com/images/I/61NLiSJDeiL._AC_SL1500_.jpg',
    'https://amzn.to/4dFoiu8',
    'Amazon',
    'affiliate',
    true,
    280,
    now(),
    now()
  ),
  (
    'prod-ludylops-base-carregamento-dualsense',
    'base-carregamento-dualsense',
    'Base de carregamento DualSense',
    'videogames',
    'Base oficial para carregar controles do PlayStation 5 e manter tudo pronto para jogar.',
    'https://m.media-amazon.com/images/I/41y-G-g+dVL._AC_SL1500_.jpg',
    'https://amzn.to/4dwh8tr',
    'Amazon',
    'affiliate',
    true,
    290,
    now(),
    now()
  ),
  (
    'prod-ludylops-mouse-logitech-g305-lilas',
    'mouse-logitech-g305-lilas',
    'Mouse Logitech G305 lilás',
    'perifericos',
    'Mouse sem fio leve e preciso para jogar, trabalhar e manter a mesa com menos cabos.',
    'https://m.media-amazon.com/images/I/51z74wV2iHL._AC_SL1500_.jpg',
    'https://amzn.to/4uYar90',
    'Amazon',
    'affiliate',
    true,
    300,
    now(),
    now()
  ),
  (
    'prod-ludylops-mop-flat-electrolux',
    'mop-flat-electrolux',
    'MOP Flat Electrolux Menalux',
    'acessorios',
    'MOP com refil de microfibra para limpar a casa com praticidade e manter a rotina menos trabalhosa.',
    'https://m.media-amazon.com/images/I/41TT01bPAYL._AC_SL1000_.jpg',
    'https://amzn.to/4nHOsRA',
    'Amazon',
    'affiliate',
    true,
    310,
    now(),
    now()
  )
ON CONFLICT ("slug") DO UPDATE SET
  "id" = EXCLUDED."id",
  "name" = EXCLUDED."name",
  "category" = EXCLUDED."category",
  "context" = EXCLUDED."context",
  "image_url" = EXCLUDED."image_url",
  "href" = EXCLUDED."href",
  "store_label" = EXCLUDED."store_label",
  "link_kind" = EXCLUDED."link_kind",
  "is_active" = EXCLUDED."is_active",
  "sort_order" = EXCLUDED."sort_order",
  "updated_at" = now();
